#!/usr/bin/env python3

import os
from os import path

import json
import subprocess
import tempfile
import glob
import shutil

import click

# https://gist.github.com/SteveClement/3755572
def get_dirsize(start_path = '.'):
	total_size = 0
	for dirpath, dirnames, filenames in os.walk(start_path):
		for f in filenames:
			fp = os.path.join(dirpath, f)
			total_size += os.path.getsize(fp)
	return total_size

def load_config(ctx, recipe):
	ctx['json'] = json.load(recipe)

def copy_files(ctx):
	for filepath in ctx['json']['files']:
		buildpath = path.normpath(path.join(ctx['build_dir'], filepath))
		tmppath = path.normpath(path.join(ctx['tmp_dir'], ctx['json']['files'][filepath]))

		if path.isfile(buildpath): # if buildpath is a file, simply copy it
			os.makedirs(path.dirname(tmppath), exist_ok=True)
			shutil.copy2(buildpath, tmppath)
		elif path.isdir(buildpath): # if buildpath is a dir, glob for files
			globpath = buildpath

			if not '*' in globpath:
				globpath = path.join(buildpath, '**') # fallback if no * is included

			globs = glob.glob(globpath, recursive=True)

			for filebuildpath in globs:
				relpath = path.relpath(filebuildpath, buildpath)
				fileoutpath = path.normpath(path.join(tmppath, relpath))

				if path.isfile(filebuildpath): # if globbed path is a file, simply copy it
					os.makedirs(path.dirname(fileoutpath), exist_ok=True)
					shutil.copy2(filebuildpath, fileoutpath)
				elif path.isdir(filebuildpath): # if globbed path is a directory, create it with correct stats and mode
					os.makedirs(fileoutpath, exist_ok=True)
					shutil.copystat(filebuildpath, fileoutpath)
					shutil.copymode(filebuildpath, fileoutpath)
	
	ctx['size'] = get_dirsize(ctx['tmp_dir']) # cache size of directory without meta_dir

def create_meta_dir(ctx):
	ctx['meta_dir'] = path.join(ctx['tmp_dir'], 'DEBIAN')

	os.mkdir(ctx['meta_dir']) # make meta_dir

	# cache paths
	path_changelog = path.join(ctx['meta_dir'], 'changelog')
	path_compat = path.join(ctx['meta_dir'], 'compat')
	path_control = path.join(ctx['meta_dir'], 'control')
	path_copyright = path.join(ctx['meta_dir'], 'copyright')

	# create DEBIAN/changelog
	with open(path_changelog,	"w+") as f:
		contents = '{} ({}) UNRELEASED; urgency=low binary-only=yes\n'.format(ctx['json']['name'], ctx['json']['version'])
		contents += '\n'

		for change in ctx['json']['changes']:
			contents += '  * {}\n'.format(change)
		contents += '\n'

		contents += ' -- {} <{}>  {}\n'.format(ctx['json']['maintainer'], ctx['json']['email'], ctx['json']['changed_by'])
		contents += '\n'

		f.write(contents)

	# create DEBIAN/compat
	with open(path_compat,	"w+") as f:
		f.write('11') # require debhelper >= 11

	# create DEBIAN/control
	with open(path_control,	"w+") as f:
		contents = 'Package: {}\n'.format(ctx['json']['name'])
		contents += 'Version: {}\n'.format(ctx['json']['version'])
		contents += 'Depends: {}\n'.format(ctx['json']['depends'])
		contents += 'Section: {}\n'.format(ctx['json']['section'])
		contents += 'Priority: optional\n'
		contents += 'Architecture: {}\n'.format(ctx['json']['arch'])
		contents += 'Installed-Size: {}\n'.format(ctx['size'])
		contents += 'Maintainer: {} <{}>\n'.format(ctx['json']['maintainer'], ctx['json']['email'])
		contents += 'Description: {}\n'.format(ctx['json']['description'])
		
		f.write(contents)

	# create DEBIAN/copyright
	with open(path_copyright,	"w+") as f:
		f.write('') # stays empty

def build_deb(ctx):
	ctx['out_file'] = '{}_{}_{}.deb'.format(ctx['json']['name'], ctx['json']['version'], ctx['json']['arch'])
	ctx['out_path'] = path.join(ctx['out_dir'], ctx['out_file'])

	subprocess.call('fakeroot dpkg-deb -b "{}" "{}"'.format(ctx['tmp_dir'], ctx['out_path']), executable=ctx['json']['shell'], shell=True)

	if path.isfile(ctx['out_path']):
		print('Generated package {}.'.format(ctx['out_path']))
	else:
		print('Something went wrong..')

def create_deb(ctx):
	ctx['tmp_dir'] = tempfile.mkdtemp() # create tmp_dir to work in

	copy_files(ctx) # copy the files defined in the recipe to the tmp_dir
	create_meta_dir(ctx) # create the corresponding metadata in tmp_dir/DEBIAN
	build_deb(ctx) # build the deb file

	shutil.rmtree(ctx['tmp_dir']) # finally remove the tmp_dir to free space

@click.command()
@click.argument('recipe', type=click.File(mode='r'))
@click.argument('build-dir', type=click.Path(exists=True, dir_okay=True))
@click.argument('out-dir', type=click.Path(exists=True, dir_okay=True, writable=True))
def run(recipe, build_dir, out_dir):
	ctx = {
		'build_dir': path.abspath(build_dir),
		'out_dir': path.abspath(out_dir)
	}

	load_config(ctx, recipe)
	create_deb(ctx)

if __name__ == '__main__':
	run()
